<header id="site-header" class="site-header">
    <div class="logo">
      <a href="#"><img src="theme/images/logo.png" alt=""></a>
    </div>
    <a href="#" class="btn-menu"><span></span></a>

  <div class="social">
    <p>Let Your Voice Be Heard</p>
    <ul>
      <li class="soc-1"><a href="https://www.facebook.com/Modernize-Oklahoma-1554651044827438/?fref=ts"></a></li>
      <li class="soc-2"><a href="https://twitter.com/ModernizeOK"></a></li>
    </ul>
  </div>
    <nav class="nav">
      <ul class="menu">
        <li><a href="#why-vote">Why Vote Yes</a></li>
        <li><a href="#faq"> FAQ </a></li>
        <li><a href="#contact">Contact your Representative</a></li>
        <li><a href="#updated">Keep Me Updated</a></li>
      </ul>
    </nav>
</header>